### ISSUE TITLE
新方案(无DAG消息结构)中各个频道数据结构

### ISSUE THREAD

**Issue by cuitaixiang** [Tau-Coin/dhtTAU#35]
以X,Y两个节点为例，对X来说总共需要三个频道：
1， XY聊天数据频道
      数据结构{List<byte[]> hashList}, list内为截取的按时间顺序排列的双方聊天消息的两字节哈希，双方通过比对可知对方缺少的哈希，从而知道缺少的消息
2，XY数据交换频道
      数据结构{List<Message> messageList }，list内为对方缺少的消息集合，根据情况尽量装满
3，X的多设备通信频道
      数据结构{List<byte[]> friendList}, list内为我的好友，如果放不下，可以轮转put，多设备通过get并比对发现并添加新好友

**Comment by cuitaixiang** [comment]
XX频道数据结构：
    { BigInteger timestamp;
    List<byte[]> friendList ;
    List<GossipItem> gossipItemList }
XY频道数据结构：
{ BigInteger timestamp;
    List<byte[]> hashList }

**Comment by wuzhengy** [comment]
XX 频道就是每个节点自己的gossip频道。数据里面包括：本设备代码，一个随机选取的朋后列表中的朋友全地址，自己发出的消息immutable hash，推荐的其他朋友的状态信号（上线，有消息）
XY 频道就是每个通信对，索引最近消息的immutable hash的截取段，本设备代码。

**Comment by wuzhengy** [comment]
XY 和 YX的内容是应该等价的，如果发生不对准，就是需要同步操作。

**Comment by wuzhengy** [comment]
XX 频道就是每个节点自己的gossip频道。数据里面包括：本设备代码，一个随机选取的朋后列表中的朋友全地址，推荐的其他朋友的消息，一个随机选取的在线朋友（保证如果没有朋友发出消息，这个地址用于继续遍历）
XY 频道就是每个通信对，索引最近消息的immutable hash，本设备代码。

**Comment by wuzhengy** [comment]
GossipItem包括{sender, receiver, timestamp}，不管是有新消息发出了还是有新同步需求，都可以通过将该时间戳置为最新（时间戳的新旧就是让别人访问我的信号），然后通过gossip传播出去，对方通过第三方发现更新的时间戳就来index频道取数据比对
即gossip里发现有新消息peer，就去index频道取数据，同时说明该节点在线，也可以去其gossip取数据

**Comment by wuzhengy** [comment]
如果在区块链情况下：XX频道，会变成 XX(chainID)频道，发布自己的消息，区块同步和传播其他链相关的消息。XY(ChainID) 和 YX(ChainID)这类频道就不需要了。看起来区块链情况下，频道结构比点对点要简单。
由于我们重载了mutable get的方法，返回值是数组，不再是单一数据，所以信息量要比基础API设计要多些，更加适合有频率的mutable 数据更新。

**Comment by wuzhengy** [comment]
XX 频道就是每个节点自己的gossip频道。数据里面包括：
1. 本设备代码
2. 如果与Y有“即时通信对话框”状态，显示这个XY状态
2. 一个随机选取的朋后列表中的朋友全地址
3. 推荐的其他朋友Z的状态信号（ZZ在线，有ZY通信同步消息，有“ZY类即时通信对话框状态”）

**Comment by wuzhengy** [comment]
新信号体系设计
* “在线和同步”思路，不是“消息驱动”思路。两个设备如果间隙的不在线时，新消息难以定义。使用本节点布隆过滤器来摘要，作为同步的驱动基础，和给未来区块链提供消息历史。“在线信号“作为信号来驱动同步，包括自己时间戳，朋友列表和在线时间戳。
* 不存在自己和远程节点的区别，对于一个设备来说其实X和Y都是平等的，都是朋友列表中的一员。X也可以对X发送消息，类似微信的自己的暂存空间。
* libtorrent immutable data 数据设计不适合我们，immutable put无法优化，随机的hash对于DHT的节点存储资源消耗大。mutable节点存储可以重复覆盖。
* 新主循环步骤：每次主循环a. 随机get YX 数据， b. 数据回来后比较YX布隆过滤器，如果XY和YX布隆过滤器一致，就发出本节点“在线信号”；如果不一致就发出对方没有的数据（根据布隆过滤器筛选，随机选择一个）。c. 如果auth=1; YX时间戳显示对方不在线，比如5分钟前，则在主循环中标志对于这个YX跳过30秒后，再get。
* 图片格式改成非渐进集合，不内涵序列，适合布隆过滤器的特征。
* 区块链考虑：Y-”blockchainID” mutable data, 这个mutable data的bloom filter 摘要整个社区消息历史。community member会收集其他peer不同时间的bloom filter，在发生私有链打击时，可以查阅社区历史的filter来判断是否是私有链。
* 区块链数据同步是一种点对点基础上的对话协议，可以理解成一个图片的传输。
* 区块链可以用不同的session，和朋友列表点对点分开。

**Comment by wuzhengy** [comment]
在线信号：发送方过滤器，接受方过滤器，自己的朋友列表过滤器，自己的chat状态和时间戳（用于推荐），自己打听到的和接受方正在通信的朋友ID。

**Comment by wuzhengy** [comment]
POT blockchain idea:
TAUID_ChainID mutable data
1. Blocks: tips and history of own view of the chain; block bloom filter and demand. Miners has incentive to share blocks. 
2. Transactions: provide transactions of own as sender or receiver, transaction capture is selfish. transaction pool bloom filter. Miner has no incentive to share other's transactions.

**Comment by wuzhengy** [comment]
transaction pool: messages and transaction. each peer only has incentive to send own transactions, if own transactions are not in other peers transaction pool bloom filter.

**Comment by wuzhengy** [comment]
Bloom filter is a pre-voting scheme, when a node come into community, it will collect the blockchain mutable range bloom filter from all nodes.  upon see a new chain, first thing is checking whether the immutable point of the chain in the community members bloom filters, if not then discard it. this is a very fast way to admit a chain for sync up. 
Each blockchain member will publish its mutable range bloom filter.

**Comment by wuzhengy** [comment]
消息数据：发送方，接收方，时间戳，子结构nonce。用布隆过滤器交换数据的本质是cache最近通信信息，双方都有责任保存和维护，同样在区块链里面，每个peer都有责任维护交易池数据。超过记录数的时候，要获得这些消息，要通过特殊通信命令放在“在线消息”里面，比如demand block。

**Comment by wuzhengy** [comment]
在线信号调整策略：XY类型信号本质其实不是在线信号，而是“有新消息”通知信号；XX才是X的在线信号。主循环在get YX 后，如果XY和YX过滤器相等，这个是大多数情况，节点不应该put XY信号，这样可以节约流量。put XY信号只有在过滤器不同情况下才发生。所以真的消耗流量的只有GET。对于我们系统其实不用管对方是否在线，只要有对方最后一次“有新消息”的时间戳就行了。所以可以把现在onlineSignal换成newMsgSignal

**Comment by wuzhengy** [comment]
有回执机制后，get 为空，应该是没有动作。当Y在线时，X没有收到回执，才put直到收到回执。当Y不在线就是YX为空，X就算没有收到回执，也没有必要执行put。 继续get就行。get总是需要的。以后我们可以发展出light get，就是不要8个，1个就行作为基本信号，这个现在不急的思考。属于优化范围。

**Comment by wuzhengy** [comment]
在区块链社区情况下， X get Y-chainID mutable data, 这里面包括Y-chainID消息的过滤器，当前区块链过滤器，消息和demand数据集合。X根据这些数据准备put X-chainID的数据集合，自己的过滤器，社区要的消息和自己的demand。

**Comment by wuzhengy** [comment]
YX类别是“新消息变动”信号
XX类别是“在线信号”

**Comment by wuzhengy** [comment]
在每个消息中增加小布隆过滤器和时间戳。这样每次主循环get，都会发现对方数据接受情况，可以大幅度节约流量。

**Comment by wuzhengy** [comment]
publish mutable data会首先放入NewMsgSignal, 然后再根据目前掌握情况看对方缺失哪些消息，和NewMsgSignal一起凑够8个以内的put item，现在会触发publish mutable data的情况有：
1. get为空, 
2. 自己有新消息发出
3. 拿到对方新NewMsgSignal, 发现对方有缺少的消息
4. 拿到对方新NewMsgSignal, 发现对方凭据对不上

新NewMsgSignal的标准是更新或者一样新
两个节点互相在对方不在线的时间上线，因此也会根据情况put一部分数据

**Comment by wuzhengy** [comment]
为了避免双方都沉默的死锁，get 得到empty和旧时间戳时不会触发put，我们可以在每10次get YX，第11次就直接put XY，这样不增加流量，同时避免沉默。

**Comment by wuzhengy** [comment]
https://github.com/Tau-Coin/dhtTAU/issues/32#issuecomment-804150465Coin/dhtTAU/issues/35#issuecomment-803922948
blockchain data replication vs transaction/msg pool sync

**Comment by wuzhengy** [comment]
朋友列表分级：
1. 当前正在通信朋友， 70%的资源
2. 本周通行过的朋友，70%的资源
3. 其他，30%的资源

**Comment by wuzhengy** [comment]
在主循环的一次执行中，每次get都应该会有对应的put触发，所以从多次循环迭代层面来看，每次主循环只需要同时异步触发get和put。具体数据的交叠由动态执行结果来平衡。纠正一下，put是每次必须要做的，现在可以精细控制alpha来调整put的次数。我们所有的get和put都是有限N步骤递归，让N=put set里面有效数据个数，就不会造成流量失控。以前我们每10次get，一次put，不如现在控制主循环每次执行的alpha put来的及时。 沉默期间，put set为空，alpha成为0，我们可以把invoke次数设置成1.（alphs 0对1， 1对2...0
对于XX类型，一秒之内的数据都是有效的，就算表达的内容不同有冲突，也是要兼顾冲突。类似逻辑，YX的最后时间戳前1s也应该是有效的。对于每个通信对，比如YX来说，get YX时的子got-data，都会把要需要put的数据放入一个全局list，这个list最后转化成8个1k的item，超过容量，早入队的就顶出了。如果从子got-data判断不需要put，则放入在put执行时，每次只需要snapshot copy这个list，然后清空，再执行put即可，这个时候put的次数是受到list长度控制的， N < 8。

**Comment by wuzhengy** [comment]
推荐gossip信号判断：节点把当前正在对话的通信对的布隆过滤器放在在线信号里，被推荐出去后，其他目标节点收到这个信号后，先比较下这个过滤器是否有新内容，如果没有就不接受，走随机路径；如果有，就本次主循环机会给到这个推荐。
在线信号中增加这个gossip信号，类似以前的设计，区块链上朋友节点数量非常大，没有GOSSIP很难提高效率。

**Comment by wuzhengy** [comment]
推荐gossip信号可能带来不安全性，可以就一级推荐，就是转发一级。推荐的进入二级朋友循环表，享受本周通信过的朋友的待遇。

**Comment by wuzhengy** [comment]
可能是在线信号被淹没了，很长一段时间get只能获得消息，不能获得在线信号。非常奇怪，不知道哪里出问题。把在线信号放在随机put位置不知道是否好，目前放在第一个位置可能在路由表里面会被局部最优保持不动。

**Comment by wuzhengy** [comment]
当消息很多时，在线信号被淹没；当消息一条条发，就还是有在线信号。看来是如此情况。第一支位置的局部最优导致联通不上。所以消息应该是打乱发送。

**Comment by wuzhengy** [comment]
当get没有新信号，从本地去上次消息put的策略我觉得对流量不友好。我们的get功能肯定是搞得定的。反而，加上设备ID的5分钟我觉得很重要。其实考虑到时差和全球很多时区因素，我们的5分钟太窄了，应该调到6小时，我们只对最新的设备时间做处理，会多用内存，但是会适应各种时间情况。 另外我们现在short time out 策略有变化，主循环1.6的控制还是改为1s.

**Comment by wuzhengy** [comment]
精简在线信号，如果目标频率是10hz，在线信号里面的任何信息都会造成流量很大的消耗。20字节的node ID，每秒就会消耗200 bytes，如果是通信对，400字节。这个一天下来就是近40mbyte。 所以考虑如下精简：
1. 不做gossip其他节点的传递。
2. 尽可能不传levensten数组，当数组hash变化时，再传数组。
3. payload 寻址信号在有数据时再传递。
在区块情况下，学习unchoke机制，唯一利用 chainID- nodeID 通信对来组成通信小组来交换信息，也不用gossip。
